### ISSUE TITLE
auth-ldap issue with PHP 5.6.20 and osticket 1.10-rc3

### ISSUE THREAD

**Issue by eproudfit** [osTicket/osTicket-plugins#105]
When I upgraded my PHP code and installed the OSticket 1.10-rc3, the auth-ldap plugin stopped working.

The current plugin version:  
Authentication :: LDAP and Active Directory
Latest Stable Release, v0.6.2 Released April, 10th, 2015

When trying to set it up to authenticate to our Active Directory

This results  in a error 500 page.

The first problem was this error in the log files:

Access level to Net_LDAP2_Schema::__construct() must be public (as in class PEAR)  in phar:///<path to osticket install>/include/plugins/auth-ldap.phar/include/Net/LDAP2/Entry.php on line 0

I extracted the auth-ldap.phar file into a working directory.

I modified the Net/LDAP2/<files> that had the 'protected  function __construct ...' to be
'public __construct ...'

I repacked the phar, put into the include/plugins directory, and tried to setup. 

This is the error that is shown in the logs:
PHP Fatal error:  Call to undefined method Net_LDAP2::PEAR()

The error 500 page also shows up, along with the undefined method error above when trying to save the configuration of the plugin.

Here is what I did to fix the issue:

Ok.  So the problem is that the Net_LDAP2 functions rely on Net_LDAP

On a Debian 8 system this is what I did:
I used: 
apt-get install php-net-ldap2 php-net-ldap

These files are in /usr/share/php/Net

I copied the directory files from /usr/share/php/Net/\* to my phar working directory (where I had extracted the original auth-ldap.phar plugin)
I repacked the phar and copied it to the osticket include/plugins directory.
I was then able to set the AD info and save without errors.
Enabled the plugin and then tested authentication.  I was successful in logging in with my AD credentials.

I hope this info helps the devs update the plugin to work with the new versions of PHP and OSticket.

**Comment by ntozier** [comment]
Good report.  Only thing that I see missing is the version of the plugin that you were running.

**Comment by eproudfit** [comment]
Added that.

Here is other info that may /may not be of interest.

Server Information
osTicket Version    v1.10-rc.3 (907ec36) —  Up to date
Web Server Software Apache
MySQL Version   5.5.49
PHP Version 5.6.22-0+deb8u1

**Comment by ntozier** [comment]
Great!  Thanks for the update.

**Comment by mercury00** [comment]
Using osticket 1.9.14 and ldap auth 0.6.2, I notice that the following files complain about protected function __construct that thinks it should be public function __consctuct in these files:

auth-ldap/include/NET/LDAP2/Entry.php
    the referenced code on line 149 is: 
protected function __construct(&$ldap, $entry = null)
      which I changed to 'public function' instead of 'protected function'

auth-ldap/include/NET/LDAP2/Schema.php
  line 112:
protected function __construct()

auth-ldap/include/NET/LDAP2/RootDSE.php
  line 44:
protected function __construct(&$entry)

**Comment by mercury00** [comment]
However, replacing them with public doesn't fix the plugin, it still crashes with an error and does not work. 

PHP Fatal error:  Call to undefined method Net_LDAP2::PEAR() in phar:///web/auth-ldap.phar/include/Net/LDAP2.php on line 232, referer: http://localhost/osticket/scp/plugins.php?id=1

**Comment by ntozier** [comment]
So I was experiencing this same issue on our 1.10rc3 install.  I upgrade to the 0.6.2 plugin and that didn't help.  I was getting this error:
[08-Aug-2016 14:26:40 UTC] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in C:\path\removed\include\plugins\auth-ldap\include\Net\LDAP2\RootDSE.php on line 238

Doing some googling on this, I went out and downloaded the newer version of LDAP2.  You can get that here: https://pear.php.net/package/Net_LDAP2

I drilled down to /include/plugins/auth_ldap/include/Net and placed the contents of the downloaded file there. (I also copied the current contents there to a folder called OLD first!).

The result: searching now appears to be mostly working [which means I can open tickets again].

Now I am getting the following error:
[08-Aug-2016 16:08:06 UTC] PHP Fatal error:  Uncaught exception 'OrmException' with message 'Union queries must have matching values counts' in C:\path\removed\include\class.orm.php:1282
Stack trace:
#0 C:\path\removed\include\ajax.users.php(90): QuerySet->union(Object(QuerySet))
#1 [internal function]: UsersAjaxAPI->search()
#2 C:\path\removed\include\class.dispatcher.php(145): call_user_func_array(Array, Array)
#3 C:\path\removed\include\class.dispatcher.php(38): UrlMatcher->dispatch(false, Array)
#4 C:\path\removed\include\class.dispatcher.php(120): Dispatcher->resolve(false, Array)
#5 C:\path\removed\include\class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#6 C:\path\removed\scp\ajax.php(262): Dispatcher->resolve('/users')
#7 {main} thrown in C:\path\removed\include\class.orm.php on line 1282

But at least Search appears to be working again.

**Comment by jjjeroenski** [comment]
Same problem and steps taken like in the post above from ntozier, also running 1.10rc3 & 0.6.2 AD plugin Running at PHP7  & Ubuntu 16.4.  Also did the modification to solve the 500 error page. --> OK

But ==> Somebody found already a solution to get the user search functoin working with active directory?
Same error in the apache log like 'ntozier'.

> Uncaught OrmException: Union queries must have matching values counts in /var/www/html/support/include/class.orm.php:1282\nStack trace:\n#0 /var/www/html/support/include/ajax.users.php(89): QuerySet->union(Object(QuerySet))\n#1 /var/www/html/support/include/class.dispatcher.php(145): UsersAjaxAPI->search()\n#2 /var/www/html/support/include/class.dispatcher.php(38): UrlMatcher->dispatch('', Array)\n#3 /var/www/html/support/include/class.dispatcher.php(120): Dispatcher->resolve('', Array)\n#4 /var/www/html/support/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)\n#5 /var/www/html/support/scp/ajax.php(262): Dispatcher->resolve('/users')\n#6 {main}\n  thrown in /var/www/html/support/include/class.orm.php on line 1282,

this part doesn't work anymore:

![image](https://cloud.githubusercontent.com/assets/671920/17971962/40add3e0-6add-11e6-97c1-7e78f383d393.png)

**Comment by jdelhome3578** [comment]
@ntozier can you share your compiled phar file?

**Comment by ntozier** [comment]
I never recompiled it as a phar I left it unphared as a directory.

**Comment by lafaurie** [comment]
I think the problem is for users how are in invited state because I tested with others how are in active state and work, tested 1.10-rc3

**Comment by tjuberg** [comment]
Upgraded our osTicket to 1.10 final alongside 0.6.2 of the LDAP plugin today, and are now our agents are unable to log in with the error:
`PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar:///<path>/osticket/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 0`

This is on Debian 8 with php version 5.6.27+dfsg-0+deb8u1

Are there any plans to resolve this issue which dates back to June or do we need to restore from backup and roll back?

**Comment by ntozier** [comment]
The fix is in this thread.
see comment https://github.com/osTicket/osTicket-plugins/issues/105#issuecomment-238293291

**Comment by foamrider** [comment]
Had to restore from backup. We use LDAP for all of our agents and are completely dependent on this plugin. Tried using the latest phar-plugin, updating to latest packages on Ubuntu 14.04, running PHP5. Subscribing on this issue, waiting to upgrade until this is fixed.

**Comment by ntozier** [comment]
@drtomasso did you apply the fix in the thread that you posted to?  (this one)

**Comment by foamrider** [comment]
@ntozier Tried installing `php-net-ldap2` from repository, but no change. We use the compiled version (phar) of the plugin.

**Comment by tjuberg** [comment]
I ended up cloning the repo and following the build instructions to generate a phar file which contained updates versions of the PEAR libraries used.

Had to edit make.php to change http to https, but otherwise it was rather straightforward.
So it seems the proper fix is for osTicket to just rebuild and publish an updated phar file.

Including my rebuilt one which seems to work, but I take no responsibility if it blows up anything else.
[auth-ldap.zip](https://github.com/osTicket/osTicket-plugins/files/567601/auth-ldap.zip)

sha256sum:
6fce4b355e2e8c2c80f0387bf29af29c3b67f387ba6cda51dec5d1a49656b146  auth-ldap.phar

**Comment by ntozier** [comment]
@TJuberg I agree.  I've pinged the devs and asked them to do so.

**Comment by shausman** [comment]
@TJuberg Thanks for that, my compiling-fu is weak. Works 95% (still getting a 422[nothing in error log] but everything seems to be working well).

**Comment by demogar** [comment]
This used to work, but I upgraded to PHP 7 and latest osTicket and it's not working anymore. Tried several ways (including those on this pose) to make it work with no luck.

* osTicket Version: 1.10
* PHP Version: 7.0
* OS: Ubuntu 16.04

**Stack Trace:**

```
2017/01/26 18:55:12 [error] 10648#0: *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function bind() on null in phar:///home/osticket/upload/include/plugins/auth-ldap.phar/authentication.php:220
Stack trace:
#0 phar:///home/osticket/upload/include/plugins/auth-ldap.phar/authentication.php(427): LDAPAuthentication->authenticate('user', 'password')
#1 /home/osticket/upload/include/class.auth.php(235): StaffLDAPAuthentication->authenticate('user', 'password')
#2 /home/osticket/upload/scp/login.php(47): AuthenticationBackend::process('user', 'password', Array)
#3 {main}
  thrown in phar:///home/osticket/upload/include/plugins/auth-ldap.phar/authentication.php on line 220" while reading response header from upstream, client: 10.252.167.96, server: <ip>, request: "POST /scp/login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "<ip>", referrer: "/scp/login.php"
```

**Comment by barresoft** [comment]
I had this problem after update osTicket to 1.10 

This was the solution for me:
1) install the latest LDAP plugin version (v0.6.3 )
2) Do this modifications to ajax.users.php file as follow:

https://github.com/osTicket/osTicket/pull/3456/files
