### ISSUE TITLE
Amazon S3 plugin -  example of the configuration

### ISSUE THREAD

**Issue by Kardell** [osTicket/osTicket-plugins#143]
Hi All,
Please can someone give an example what exact S3 values should go to these fields?
There is no configuration validation, I don't know if settings I save are correct.
I am unable to communicate with the S3 bucket. Communication seems dead.
Thank you
Best regards,

**Comment by jahir3819** [comment]
It is sad that this S3 plugin is not working anymore.
All the issues reported regarding to S3 have been neglected so far

**Comment by ntozier** [comment]
@jahir3819 Can you be more specific?

**Comment by jahir3819** [comment]
I have upgraded to the Osticket latest version osTicket (v1.10.4)., Since then Amazon S3 is not working. 
Once i filled below details and click save changes.We are getting HTTP 500 Error as a response

![image](https://user-images.githubusercontent.com/33779169/44038703-58be0390-9ee5-11e8-8513-7ad141ce915d.png)

**Comment by jahir3819** [comment]
I have upgraded to the Osticket latest version osTicket (v1.10.4)., Since then Amazon S3 is not working.
Once i filled below details and click save changes.We are getting HTTP 500 Error as a response
![image](https://user-images.githubusercontent.com/33779169/44038794-9876e812-9ee5-11e8-84d9-e553363c5b64.png)

**Comment by ntozier** [comment]
Your environment details?
Details of the 500 error from your webserver logs?
Any PHP errors being thrown?

**Comment by jahir3819** [comment]
Apache Version	2.4.34
PHP Version	7.0.31
MySQL Version	10.0.36-MariaDB
Architecture	x86_64
Operating System	linux

details of 500 Error, "Unable to handle the request"
No PHP Errors
******************

In order to add you further on this issue, Since details were not filled in Amazon S3 Storage deails under "Manage->Plugins"
I was able to select the S3()  in Storage attachments under "Settings->Systems". WHen i click save changes. It throws "Unable to update settings. Correct any errors below and try again."

"* /tmp/guzzle-cacert.pem MD5 mismatch: expected 349ba2d6964db9ca558c9e1daf38e428 but got 6c81b1339b320190689e4c2d594ca67f"


![image](https://user-images.githubusercontent.com/33779169/44045743-8222694e-9ef7-11e8-87b0-620e429b58c0.png)


![image](https://user-images.githubusercontent.com/33779169/44045759-8eb55630-9ef7-11e8-9abf-0a4e7deea460.png)

**Comment by jahir3819** [comment]
Any updates?

**Comment by jahir3819** [comment]
Server Information
--
osTicket Version | v1.10.4 (035fd0a) —  Up to date
Web Server Software | Apache
MySQL Version | 10.1.31
PHP Version | 7.0.31

**Comment by jahir3819** [comment]
Below is the PHP error logged in the server

[18-Aug-2018 06:32:07 UTC] PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/vdprgyjn/public_html/support/include/class.translation.php on line 674
[18-Aug-2018 06:32:07 UTC] PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/vdprgyjn/public_html/support/include/class.nav.php on line 227
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant PriorityField - assumed 'PriorityField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.forms.php on line 2300
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant DepartmentField - assumed 'DepartmentField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.forms.php on line 2404
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant AssigneeField - assumed 'AssigneeField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.forms.php on line 2525
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant TicketStateField - assumed 'TicketStateField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.forms.php on line 2615
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant TicketFlagField - assumed 'TicketFlagField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.forms.php on line 2674
[18-Aug-2018 06:32:07 UTC] PHP Warning: Use of undefined constant SelectionField - assumed 'SelectionField' (this will throw an Error in a future version of PHP) in /home/vdprgyjn/public_html/support/include/class.list.php on line 525
[18-Aug-2018 06:32:10 UTC] PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/vdprgyjn/public_html/support/include/class.translation.php on line 674
[18-Aug-2018 06:32:10 UTC] PHP Fatal error: Uncaught Error: Class 'Aws\S3\S3Client' not found in /home/vdprgyjn/public_html/support/include/plugins/storage-s3/config.php:87
Stack trace:
#0 /home/vdprgyjn/public_html/support/include/class.plugin.php(77): S3StoragePluginConfig->pre_save(Array, Array)
#1 /home/vdprgyjn/public_html/support/include/class.plugin.php(67): PluginConfig->commitForm(Array)
#2 /home/vdprgyjn/public_html/support/scp/plugins.php(13): PluginConfig->commit(Array)
#3 {main}
thrown in /home/vdprgyjn/public_html/support/include/plugins/storage-s3/config.php on line 87

**Comment by JediKev** [comment]
@jahir3819

Your issue is most likely PHP 7. Please downgrade to PHP 5.6.x and retest.

Cheers.

**Comment by jahir3819** [comment]
@JediKev  Yes i have also downgraded to PHP 5.6 and still it is the same

**Comment by JediKev** [comment]
@jahir3819

Have you downloaded the latest version of the plugin and reinstalled it?

Cheers.

**Comment by jahir3819** [comment]
@JediKev  Yes installed osTicket Version | v1.10.4 (035fd0a) —  Up to date and tested

**Comment by JediKev** [comment]
@jahir3819

No...the plugin.

Cheers.

**Comment by jahir3819** [comment]
@JediKev I have installed this https://github.com/osTicket/osTicket-plugins/tree/develop/storage-s3 and tested since Phar file is not supported in our server. Is there any new version than this?

**Comment by JediKev** [comment]
@jahir3819

You shouldn’t be using it like that...you’re supposed to use the phar package as it’s signed and everything. Please install the PHP phar extension so you can install the phar package from our website and retest.

Cheers.

**Comment by jahir3819** [comment]
Since i am in shared hosting. No way to have them installed phar extension.

**Comment by JediKev** [comment]
@jahir3819

Oh boy...

Well...when you downgrade to PHP 5.6 what errors do you receive?

Cheers.

**Comment by jahir3819** [comment]
Same HTTP 500 Error on browser. Flooded with the above PHP Error

**Comment by JediKev** [comment]
@jahir3819

Post a screenshot of you dashboard > information page whilst you are using PHP 5.6.

Cheers.

**Comment by jahir3819** [comment]
Server Information
--
osTicket Version | v1.10.4 (035fd0a) —  Up to date
Web Server Software | Apache
MySQL Version | 10.1.31
PHP Version | 5.6.37

**Comment by jahir3819** [comment]
![image](https://user-images.githubusercontent.com/33779169/44300205-4b4cf780-a2d1-11e8-95ca-8e1b38884cb8.png)

**Comment by JediKev** [comment]
@jahir3819

So, looking at it again, _most_ of your errors are due to PHP 7. See the thread below:
https://github.com/osTicket/osTicket/issues/4237

The only error that is not _necessarily_ due to PHP 7 is:
```
PHP Fatal error: Uncaught Error: Class 'Aws\S3\S3Client' not found in /home/vdprgyjn/public_html/support/include/plugins/storage-s3/config.php:87
```

Gotta figure out why this error occurs.

Cheers.

**Comment by jahir3819** [comment]
Where can i get V1.9 Stable version of OSticket?

**Comment by JediKev** [comment]
@jahir3819

You gotta find it on the web and it’s not recommended as it has already reached its end of life.

Cheers.
