### ISSUE TITLE
ldap-auth doesnt work

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-plugins#151]
I've bind osTicket to a Kolab Directory Server but when I try to logon HTTP error 500 comes along. I'm running  osTicket 1.10.4-115-gb218896d (b218896) on PHP 7.0.33-0+deb9u1

apache log says the following:
[Sat Dec 22 00:19:28.928353 2018] [:error] [pid 8323] [client 192.168.1.135:49316] PHP Fatal error:  Uncaught Error: Call to a member function bind() on null in /var/www/html/osticket/include/plugins/auth-ldap/authentication.php:220\nStack trace:\n#0 /var/www/html/osticket/include/plugins/auth-ldap/authentication.php(427): LDAPAuthentication->authenticate('x', 'yyy')\n#1 /var/www/html/osticket/include/class.auth.php(235): StaffLDAPAuthentication->authenticate('xxx', 'yyy')\n#2 /var/www/html/osticket/scp/login.php(47): AuthenticationBackend::process('xxx', 'yyy', Array)\n#3 {main}\n  thrown in /var/www/html/osticket/include/plugins/auth-ldap/authentication.php on line 220, referer: http://192.168.1.34/osticket/scp/login.php

as far as I can see, the credentials never arrive at the ldap server.
[22/Dec/2018:00:19:28 +0100] conn=589 fd=69 slot=69 connection from 192.168.1.34 to 192.168.1.35
[22/Dec/2018:00:19:28 +0100] conn=589 op=0 BIND dn="" method=128 version=3
[22/Dec/2018:00:19:28 +0100] conn=589 op=0 RESULT err=48 tag=97 nentries=0 etime=0
[22/Dec/2018:00:19:28 +0100] conn=589 op=1 UNBIND
[22/Dec/2018:00:19:28 +0100] conn=589 op=1 fd=69 closed - U1

Is that probably related to PHP7?

**Comment by ntozier** [comment]
osTicket does not support php7 at this time so that could be part of it.  That being said I ran php 7.0 for a little while and did not have the same problem.  What version of php 7 are you running?  7.0? 7.1? 7.2? 7.3?

**Comment by ghost** [comment]
It's PHP 7.0.33-0 and Apache version 2.4.25
I'm going to downgrade later on that week.
Merry Christmas! :)

**Comment by ghost** [comment]
I've downgraded to PHP 5.6.39 but the issue is still there. As I am not a LDAP expert I have no clue whether my config suits or not but dispite this, binding the ldap server works just fine.

This is my configuration:
default domain: soccerix.net
LDAP server: kolab01.soccerix.net (cleartext so far)
search user: cn=Directory Manager
search base: dc=soccerix,dc=net
LDAP Schema: Posix Account

The account type I try to logon with is called 'Mail-enabled POSIX User' As I've enabled error logs in bootstrap.php browser hits me up with **Fatal error: Call to a member function bind() on null in phar:///var/www/html/osticket/include/plugins/auth-ldap.phar/authentication.php on line 220**

apache2 log shows the same:
**[Fri Dec 28 12:39:31.431452 2018] [:error] [pid 17427] [client 192.168.1.135:5445] PHP Fatal error:  Call to a member function bind() on null in phar:///var/www/html/osticket/include/plugins/auth-ldap.phar/authentication.php on line 220, referer: http://192.168.1.34/osticket/scp/login.php**

LDAP server log is also the same as on PHP7.0
**[28/Dec/2018:12:39:30 +0100] conn=536 fd=67 slot=67 connection from 192.168.1.34 to 192.168.1.35
[28/Dec/2018:12:39:30 +0100] conn=536 op=0 BIND dn="" method=128 version=3
[28/Dec/2018:12:39:30 +0100] conn=536 op=0 RESULT err=48 tag=97 nentries=0 etime=0
[28/Dec/2018:12:39:30 +0100] conn=536 op=1 UNBIND
[28/Dec/2018:12:39:30 +0100] conn=536 op=1 fd=67 closed - U1**

Have you got any suggestions what to look for?

**Comment by ntozier** [comment]
My search user is "domainshortname\username".
My search base is "OU=All_Users,DC=corp,DC=domainshortname,DC=local".
note: we renamed "All Users" to "All_Users" because spaces.

I think err=48 means "INAPPROPRIATE_AUTHENTICATION".  So maybe it doesn't like the username or password provided.

**Comment by ghost** [comment]
I think that's because the username doesn't even make it to the LDAP server. Try `ldapsearch -D "" -w secret -p 389 -h yourhost -b "cn=schema" -s base "(objectclass=*)"`
results in
`ldap_bind: Inappropriate authentication (48)`
As per the log above **BIND dn=""** indicates no username has been provided to the ldap server,
but please correct me if I am wrong!

tcpdump shows that the bind request right after login comes along with username `<ROOT>` instead of given username

**Comment by ghost** [comment]
![tcpdump](https://user-images.githubusercontent.com/26025023/50519590-f8275480-0abb-11e9-8ef8-8d3eb4e0c35a.png)

**Comment by JediKev** [comment]
@tuerkasten 

The key here is `(Anonymous access is not allowed)`. It appears as though it's not passing the authentication credentials. Ensure your searchbase settings and all other credentials are indeed correct.

**One thing to try:**
Uninstall/Delete the plugin, re-install using PHP 5.6, enter all the credentials, save changes, and test again. Maybe PHP 7 borked the plugin install?

Cheers.

**Comment by ghost** [comment]
I've cleaned /include/plugins this morning and reinstalled both auth-ldap and auth-passthru. I'm gonna set this whole thing up from scratch.

cheers

**Comment by ghost** [comment]
just installed the whole thing from scratch to no avail. I can't neither login with LDAP Users nor search the directory. HTTP 500 aka `Fatal error: Call to a member function bind() on null in phar:///var/www/html/helpdesk/include/plugins/auth-ldap.phar/authentication.php on line 220`

**Comment by ghost** [comment]
is it possible authentication.php doesn't pass along credentials just as config.php?

**Comment by ghost** [comment]
leaving LDAP schema on auto-detect leads to **Fatal error: Call to a member function rootDse() on null in phar:///var/www/html/helpdesk/include/plugins/auth-ldap.phar/authentication.php on line 259**

**Comment by ghost** [comment]
I configured a Linux client to authenticate against my directory server successfully. This is the output in Wireshark.

![ssh-auth](https://user-images.githubusercontent.com/26025023/50563799-581e3500-0d20-11e9-96b5-7cec8d10f776.png)


How's the matching whether to grant access for ldap users working? I just created two users in osTicket with the same username as the uid on the directory server. Is that correct?

**Comment by ghost** [comment]
This before line 154 fixed it for me.

`$parmas['binddn'] = $this->getConfig()->get('bind_dn');
            $params['bindpw'] = Crypto::decrypt($this->getConfig()->get('bind_pw'),
                            SECRET_SALT, $this->getConfig()->getNamespace());`

I am not a programmer. I just did some reverse engineering with a couple of hints with some friends. Maybe a programmer could have an eye on it to adapt it to proper pro code :>

Cheers

**Comment by JediKev** [comment]
@tuerkasten 

So you just assigned `bind_dn` from db to `binddn` and then assigned the decrypted password to `bindpw`, correct?

Did you add those lines to `authentication.php`?

Cheers.

**Comment by ghost** [comment]
@JediKev 
Yes that's correct. I assigned it to `authentication.php` because `$r` in line 155 in `authentication.php` already returned `NULL`.
My configuration was to set the schema per se which is Posix. 

Cheers

**Comment by ScholtenF** [comment]
@tuerkasten You are a life saver!
