### ISSUE TITLE
OpenLDAP bind

### ISSUE THREAD

**Issue by eutampieri** [osTicket/osTicket-plugins#167]
I have installed the auth-ldap plugin but users fail to authenticate: here's the slapd's log message:
```
Feb 13 13:39:26 vps554593 slapd[17053]: conn=1707 fd=15 ACCEPT from IP=127.0.0.1:46704 (IP=0.0.0.0:389)
Feb 13 13:39:26 vps554593 slapd[17053]: conn=1707 op=0 BIND dn="" method=128
Feb 13 13:39:26 vps554593 slapd[17053]: conn=1707 op=0 RESULT tag=97 err=48 text=anonymous bind disallowed
Feb 13 13:39:26 vps554593 slapd[17053]: conn=1707 op=1 UNBIND
```
- osTicket (v1.14.1)

My configuration is:
- Default domain: example.com
- DNS Servers: empty
- LDAP servers: 127.0.0.1
- Use TLS -> no
- Search user: cn=service,dc=example, dc=com
- Password: s3cReT
- Search base: ou=People,dc=example,dc=com
- LDAP schema -> Posix account

A user's RDN looks like uid=user,ou=People,dc=example,dc=com

**Comment by JediKev** [comment]
@eutampieri 

As the error message states `err=48 text=anonymous bind disallowed` you are attempting to bind Anonymously which is not allowed in your setup. You will need to authenticate using a password to get around this.

Cheers.

**Comment by eutampieri** [comment]
First of all, thanks for your reply! I know the server doesn't allow anonymous binding: I disabled it myself. However, I thought that my settings provided an user for the binding. Where should I specify the parameters?

**Comment by JediKev** [comment]
@eutampieri 

In the Plugin settings in osTicket. Fill out all the fields and you should be good to go.

Cheers.

**Comment by eutampieri** [comment]
Please have a look at the first message, I’d included the configuration

**Comment by JediKev** [comment]
@eutampieri 

I see that, but you obviously have something configured incorrectly. I use OpenLDAP as well with no issues.
<img width="908" alt="Screen Shot 2020-02-13 at 10 59 34" src="https://user-images.githubusercontent.com/11823401/74458988-27c82600-4e50-11ea-80c2-bda605097107.png">

Cheers.

**Comment by eutampieri** [comment]
@JediKev , I see… Is the default domain related in any way to the search base?

**Comment by JediKev** [comment]
@eutampieri 

The Default Domain is the domain that the system will use to query the LDAP lookups/authentication and the Search Base is where the system will start the lookups/authentications on the LDAP server.

Cheers.

**Comment by eutampieri** [comment]
I'm not understanding… Is this true even out of an AD context?

**Comment by JediKev** [comment]
@eutampieri 

Default Domain = default domain of the OpenLDAP server.
Search Base = the base for searching in OpenLDAP (where you want to search for users).

Cheers.

**Comment by eutampieri** [comment]
I understand what the search base is, but not the default domain. Is it the BaseDN?

**Comment by eutampieri** [comment]
![ldap](https://user-images.githubusercontent.com/10284268/74777514-e85b6880-5299-11ea-9a14-044b45917236.png)
@JediKev Here's my config, it doesn't differ much from yours, and yet it binds anonymously!
Like this:
```
Feb 18 21:55:38 vps554593 slapd[17053]: conn=5884 fd=18 ACCEPT from IP=127.0.0.1:35308 (IP=0.0.0.0:389)
Feb 18 21:55:38 vps554593 slapd[17053]: conn=5884 op=0 BIND dn="" method=128
Feb 18 21:55:38 vps554593 slapd[17053]: conn=5884 op=0 RESULT tag=97 err=48 text=anonymous bind disallowed
Feb 18 21:55:38 vps554593 slapd[17053]: conn=5884 op=1 UNBIND
Feb 18 21:55:38 vps554593 slapd[17053]: conn=5884 fd=18 closed
```
as soon as I hit login

**Comment by eutampieri** [comment]
I see that the login page makes this (`curl 'https://supporto.cinemapedagna.it/scp/login.php' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0' -H 'Accept: */*' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://supporto.cinemapedagna.it' -H 'Connection: keep-alive' -H 'Referer: https://supporto.cinemapedagna.it/scp/login.php' -H 'Cookie:OSTSESSID=kkargue57mn2i6hm5k6nllmu69' -H 'TE: Trailers' --data '__CSRFToken__=454b70935b8b08b7d8475cbc499ab8fd9e0b583f&do=scplogin&userid=my_user&passwd=s3Cre1&ajax=1'`) request but it fails with HTTP 500

**Comment by eutampieri** [comment]
I see that the login page makes this (`curl 'https://supporto.cinemapedagna.it/scp/login.php' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0' -H 'Accept: */*' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://support.example.com' -H 'Connection: keep-alive' -H 'Referer: https://support.example.com/scp/login.php' -H 'Cookie:OSTSESSID=kkargue57mn2i6hm5k6nllmu69' -H 'TE: Trailers' --data '__CSRFToken__=454b70935b8b08b7d8475cbc499ab8fd9e0b583f&do=scplogin&userid=my_user&passwd=s3Cre1&ajax=1'`) request but it fails with HTTP 500

**Comment by JediKev** [comment]
@eutampieri 

>I see that the login page makes this (....) request but it fails with HTTP 500

This is because of the error: `err=48 text=anonymous bind disallowed`

You will need to resolve this error before logging in works with the Plugin Enabled. You should verify that you are using your full Bind DN and that it is valid _and_ verify that your password is valid before continuing.

Cheers.

**Comment by eutampieri** [comment]
When I save the settings, I see this in my server log:
```
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 fd=18 ACCEPT from IP=127.0.0.1:36880 (IP=0.0.0.0:389)
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 BIND dn="cn=service,dc=cinemapedagna,dc=it" method=128
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 BIND dn="cn=service,dc=cinemapedagna,dc=it" mech=SIMPLE ssf=0
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 RESULT tag=97 err=0 text=
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=1 UNBIND
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 fd=18 closed
```
So I suppose the settings are indeed correct

**Comment by eutampieri** [comment]
When I save the settings, I see this in my server log:
```
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 fd=18 ACCEPT from IP=127.0.0.1:36880 (IP=0.0.0.0:389)
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 BIND dn="cn=service,dc=example,dc=it" method=128
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 BIND dn="cn=service,dc=example,dc=it" mech=SIMPLE ssf=0
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=0 RESULT tag=97 err=0 text=
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 op=1 UNBIND
Feb 18 22:11:16 vps554593 slapd[17053]: conn=5892 fd=18 closed
```
So I suppose the settings are indeed correct.
However, the login still doesn't work

**Comment by JediKev** [comment]
@eutampieri 

Try changing `LDAP Schema:` in the Plugin settings to `Automatically Detect` and retest.

Cheers.

**Comment by eutampieri** [comment]
nope… In the meantime, thanks.
It still binds anonymously

**Comment by ntozier** [comment]
Try changing your Search user to the actual user.

DOMAIN\username
or
username@DOMAIN

**Comment by eutampieri** [comment]
Ok, even if it’s OpenLDAP?

**Comment by jgrocha** [comment]
Same error here, **after disabling LDAP anonymous searches**. Both osTicket 1.17 and 1.18 don't work after disable anonymous searches. It works with LDAP, if anonymous bind are enabled.

![image](https://github.com/osTicket/osTicket-plugins/assets/163681/0d8645b9-8bef-46c6-9a65-ba7be8c0b016)

```txt
PHP Fatal error:  Uncaught Error: Call to a member function bind() on null in phar:///var/www/ticket.geomaster.pt.siiam/include/plugins/auth-ldap.phar/authentication.php:223\nStack trace:\n#0 phar:///var/www/ticket.geomaster.pt.siiam/include/plugins/auth-ldap.phar/authentication.php(430): LDAPAuthentication->authenticate()\n#1 /var/www/ticket.geomaster.pt.siiam/include/class.auth.php(341): StaffLDAPAuthentication->authenticate()\n#2 /var/www/ticket.geomaster.pt.siiam/scp/login.php(71): AuthenticationBackend::process()\n#3 {main}\n  thrown in phar:///var/www/ticket.geomaster.pt.siiam/include/plugins/auth-ldap.phar/authentication.php on line 223, referer: https://ticket.geomaster.pt/siiam/scp/login.php
```

### Re-enabling anonymous search

```
cat cat enable_bind_anon.ldif
dn: cn=config
changetype: modify
delete: olcDisallows
olcDisallows: bind_anon
```
```
sudo ldapadd -Y EXTERNAL -H ldapi:/// -f enable_bind_anon.ldif
```

After this, the osTicket allows LDAP users to login again.

### Disabling anonymous search

```
cat disable_bind_anon.ldif
dn: cn=config
changetype: modify
add: olcDisallows
olcDisallows: bind_anon
```
```
sudo ldapadd -Y EXTERNAL -H ldapi:/// -f disable_bind_anon.ldif
```

After this, osTicket does not support LDAP authentication.

**Comment by jgrocha** [comment]
### Workaround

If anonymous bind is enabled in LDAP, users can login using LDAP if the user's authentication settings is changed from LDAP to any available backend. This just applies to existing users.

![image](https://github.com/osTicket/osTicket-plugins/assets/163681/6848dc60-5cae-4f98-90a6-cc4455c42be7)

To

![image](https://github.com/osTicket/osTicket-plugins/assets/163681/5f062a30-69a3-48ac-a094-cc77b594b636)

I just found this by mistake. It does not make sense, but it works :-)

In this case, the `ost_staff` table looks like this:
 ```
MariaDB [osticketsiiam]> select username, passwd, email, backend from ost_staff where username = 'jgr';
+----------+--------+------------------+---------+
| username | passwd | email            | backend |
+----------+--------+------------------+---------+
| jgr      | NULL   | jgr@geomaster.pt |         |
+----------+--------+------------------+---------+
1 row in set (0,000 sec)
```
No password and no backend.
