### ISSUE TITLE
make.php many error

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-plugins#188]
I get the follwoing errors when i run you commands.

php make.php hydrate
`Deprecation warning: Your package name osTicket/core-plugins is invalid, it should not contain uppercase characters. We suggest using os-ticket/core-plugins instead. Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require.pear-pear.php.net/Net_LDAP2 is invalid, it should not contain uppercase characters. Please use pear-pear.php.net/net_ldap2 instead. Make sure you fix this as Composer 2.0 will error.
`

php -dphar.readonly=0 make.php build storage-fs/
```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar 'storage-fs/.phar', file extension (or combination) not recognised or the directory does not exist in /var/www/ticket.vhs.cloud/html/include/plugins/make.php:380
Stack trace:

Phar->__construct('storage-fs/.pha...')
PluginBuilder->_build('storage-fs/', Array)
PluginBuilder->run(Array, Array)
Module->_run('make.php')

```

how to fix?

**Comment by arunas-devoro** [comment]
Remove tailing slash. this helped me.

**Comment by jjanderson** [comment]
I have the following error when I run the command `php make.php hydrate`

```
root@osticket:/var/www/osTicket/upload/include/plugins/osTicket-plugins-develop# php make.php hydrate
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php:512
Stack trace:
#0 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(643): PluginBuilder->_http_get()
#1 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(639): PluginBuilder->getComposer()
#2 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(686): PluginBuilder->ensureComposer()
#3 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(457): PluginBuilder->resolveDependencies()
#4 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(340): PluginBuilder->_hydrate()
#5 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(240): PluginBuilder->run()
#6 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(704): Module->_run()
#7 {main}
  thrown in /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php on line 512
```
Can anyone help?

**Comment by ntozier** [comment]
@jjanderson your bug report does not appear to have anything to do with the thread that you posted it on.

What version of PHP are you running?
Do you have curl enabled in your PHP?
Is there some reason why you aren't downloading pre-hydrated plugins from the official download site (https://osticket.com/download)

**Comment by jjanderson** [comment]
> @jjanderson your bug report does not appear to have anything to do with the thread that you posted it on.

errr... the error above by the OP was exactly the same.... not sure why you think that my post was posted in the wrong location... regardless, I have it sorted now anyway...

**Comment by arunas-devoro** [comment]
> I have the following error when I run the command `php make.php hydrate`
> 
> ```
> root@osticket:/var/www/osTicket/upload/include/plugins/osTicket-plugins-develop# php make.php hydrate
> PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php:512
> Stack trace:
> #0 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(643): PluginBuilder->_http_get()
> #1 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(639): PluginBuilder->getComposer()
> #2 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(686): PluginBuilder->ensureComposer()
> #3 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(457): PluginBuilder->resolveDependencies()
> #4 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(340): PluginBuilder->_hydrate()
> #5 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(240): PluginBuilder->run()
> #6 /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php(704): Module->_run()
> #7 {main}
>   thrown in /var/www/osTicket/upload/include/plugins/osTicket-plugins-develop/make.php on line 512
> ```
> 
> Can anyone help?

You missing php-curl extension.
ubuntu:
apt install php-curl

FreeBSD:
pkg isntall php74-curl    (if you use PHP 7.4, otherwise adjust version number)

**Comment by ntozier** [comment]
The two errors are:

Original posted error:
`PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar 'storage-fs/.phar'`

Your error:
`Uncaught Error: Call to undefined function curl_init()`

Either way I'm glad that you got this sorted.  Please close the issue if it is resolved.

**Comment by jjanderson** [comment]
Thanks @arunas-devoro !

**Comment by jjanderson** [comment]
i think only @hahaxd35 can close it as he opened it... I can't see the close option on this issue
