### ISSUE TITLE
make.php: _http_get silently fails

### ISSUE THREAD

**Issue by sevmonster** [osTicket/osTicket-plugins#189]
If `_http_get` fails, it does so silently. Writing the output to file results in an empty file. This can be seen in  `getComposer`, where the return code nor the phar are checked, meaning Composer is never downloaded and run, leading to this error:
```cmd
C:\src\osTicket-plugins> php make.php hydrate
Hydrating :: lib/jasig/phpcas/source => auth-cas/lib/jasig/phpcas
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(C:\src\osTicket-plugins/lib/jasig/phpcas/source,C:\src\osTicket-plugins/lib/jasig/phpcas/source): The system cannot find the path specified. (code: 3) in C:\src\osTicket-plugins\make.php:481
Stack trace:
#0 C:\src\osTicket-plugins\make.php(481): RecursiveDirectoryIterator->__construct()
#1 C:\src\osTicket-plugins\make.php(340): PluginBuilder->_hydrate()
#2 C:\src\osTicket-plugins\make.php(240): PluginBuilder->run()
#3 C:\src\osTicket-plugins\make.php(704): Module->_run()
#4 {main}
  thrown in C:\src\osTicket-plugins\make.php on line 481
```

Patch to handle it in `_http_get`:
```diff
--- a/make.php
+++ b/make.php
@@ -517,6 +517,10 @@ class PluginBuilder extends Module {
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         $result=curl_exec($ch);
         $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
+
+        if ($result === FALSE)
+            $this->fail("_http_get error: " . curl_error($ch));
+
         curl_close($ch);

         return array($code, $result);
```
`_http_get` is only used twice, one for `getComposer` and one for `_crowdin`; the latter does check the HTTP code so it should not experience this issue. If it is better to not catch it in `_http_get`, here is a patch to handle it in `getComposer`:
```diff
--- a/make.php
+++ b/make.php
@@ -642,6 +642,9 @@ class PluginBuilder extends Module {
     function getComposer() {
         list($code, $phar) = $this->_http_get('https://getcomposer.org/composer-stable.phar');

+        if ($code != 200)
+            $this->fail($code.": Bad status from getcomposer.org downloading Composer");
+
         if (!($fp = fopen(dirname(__file__).'/composer.phar', 'wb')))
             $this->fail('Cannot install composer: Unable to write "composer.phar"');
```
However, in this case the actual underlying `curl_error` is not reported, only the code. A good in-between would be writing `curl_error` to `$result` before closing the handle and returning:
```diff
--- a/make.php
+++ b/make.php
@@ -517,6 +517,10 @@ class PluginBuilder extends Module {
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         $result=curl_exec($ch);
         $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
+
+        if ($result === FALSE)
+            $result = curl_error($ch);
+
         curl_close($ch);

         return array($code, $result);
@@ -642,6 +646,12 @@ class PluginBuilder extends Module {
     function getComposer() {
         list($code, $phar) = $this->_http_get('https://getcomposer.org/composer-stable.phar');

+        // NOTE: $code should be int 0 if $result is FALSE, and if $result is FALSE we set it to curl_error
+        if ($code === 0)
+            $this->fail("Connection error downloading composer: ".$phar);
+        elseif ($code !== 200)
+            $this->fail($code.": Bad status from getcomposer.org downloading Composer");
+
         if (!($fp = fopen(dirname(__file__).'/composer.phar', 'wb')))
             $this->fail('Cannot install composer: Unable to write "composer.phar"');

```

With the third patch, here's how it looks in our environment on a fresh server:
```cmd
C:\src\osTicket-plugins>php make.php hydrate
Connection error downloading composer: SSL certificate problem: unable to get local issuer certificate
```
Without the first or third patch I was not able to see what this error was at all and was left to guess as to why `composer.phar` was empty. After resolving that error, everything worked as expected.

**Comment by sevmonster** [comment]
It has been two years and this simple-to-fix bug is still present. Last I checked it still causes `make.php` to fail silently on Windows Server installations 2019 and before without up-to-date patches and php.ini changes, maybe later versions too.

@protich @JediKev @aydreeihn
