### ISSUE TITLE
Oauth Plug-in - Deleting a user didn't remove it from ost_user_account

### ISSUE THREAD

**Issue by slysiou** [osTicket/osTicket-plugins#278]
After deleting a user created during connection using oauth provider, the new connection doesn't work.
After checking logs, I discover the issue:

[INSERT INTO `ost_user_account` SET `user_id` = 8, `timezone` = 'Europe/Berlin', `username` = '[xxx@xxx.com](mailto:xxx@xxx.com)', `backend` = 'oauth2.user.p1i1', `status` = 1] Duplicate entry '[xxx@xxx.com](mailto:xxx@xxx.com)' for key 'username'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(211): osTicket->logDBError()<br /> #1 (root)/include/class.orm.php(3482): db_query()<br /> #2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br /> #3 (root)/include/class.user.php(1220): VerySimpleModel->save()<br /> #4 (root)/include/class.user.php(1112): UserAccount->save()<br /> #5 (root)/include/class.auth.php(154): UserAccount->confirm()<br /> #6 phar://(root)/include/plugins/auth-oauth2.phar/oauth2.php(248): ClientCreateRequest->attemptAutoRegister()<br /> #7 phar://(root)/include/plugins/auth-oauth2.phar/oauth2.php(96): OAuth2UserAuthBackend->signIn()<br /> #8 phar://(root)/include/plugins/auth-oauth2.phar/auth.php(34): OAuth2UserAuthBackend->callback()<br /> #9 (root)/include/class.dispatcher.php(153): OAuth2Plugin::{closure}()<br /> #10 (root)/include/class.dispatcher.php(40): UrlMatcher->dispatch()<br /> #11 (root)/api/http.php(29): Dispatcher->resolve()<br /> #12 {main}

After removing in ost_user_account table the record. New connection works for this user.

I think deleting user was not expected in the code.
more logs on the auth0 process will be appreciated ;-)

**Comment by slysiou** [comment]
I realise this append when oauth plug configuration change between first connection and deleting user only.
