### ISSUE TITLE
Problem hydrating the plugins

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket-plugins#38]
Freshly installed Debian Wheezy, nginx and php5-(fpm|cli) from dotdeb repos. Trying to hydrate the plugins. I've rm'ed the plugin dirs I don't need:

```
root@osticket:/data/www/osticket/include/plugins# php make.php hydrate
Loading composer repositories with package information
Initializing PEAR repository http://pear.php.net
Could not load Auth 1.3.0r5: Invalid version string "1.3.0r5"
Could not load Auth 1.3.0r4: Invalid version string "1.3.0r4"
Could not load Auth 1.3.0r3: Invalid version string "1.3.0r3"
Could not load Auth 1.3.0r2: Invalid version string "1.3.0r2"
Could not load Auth 1.3.0r1: Invalid version string "1.3.0r1"
Could not load Auth_PrefManager2 2.0.0dev1: Invalid version string "2.0.0dev1"
Could not load Contact_AddressBook 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Gtk_ScrollingLabel 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Image_Graph 0.3.0dev4: Invalid version string "0.3.0dev4"
Could not load Image_Graph 0.3.0dev3: Invalid version string "0.3.0dev3"
Could not load Image_Graph 0.3.0dev2: Invalid version string "0.3.0dev2"
Could not load Image_Graph 0.3.0dev1: Invalid version string "0.3.0dev1"
Could not load Net_MPD 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load PEAR 1.9.5dev1: Invalid version string "1.9.5dev1"
Could not load Structures_DataGrid 0.9.1dev1: Invalid version string "0.9.1dev1"
Could not load Structures_DataGrid_DataSource_Array 0.2.0dev1: Invalid version string "0.2.0dev1"
Could not load Structures_DataGrid_DataSource_DataObject 0.2.2dev1: Invalid version string "0.2.2dev1"
Could not load Structures_DataGrid_DataSource_XML 0.2.1dev1: Invalid version string "0.2.1dev1"
Could not load Structures_DataGrid_Renderer_CSV 0.1.5dev1: Invalid version string "0.1.5dev1"
Could not load Structures_DataGrid_Renderer_XML 0.1.4dev1: Invalid version string "0.1.4dev1"
Could not load Structures_Form 0.8.0devel: Invalid version string "0.8.0devel"
Could not load Structures_Form_Gtk2 0.8.0devel: Invalid version string "0.8.0devel"
Could not load Structures_DataGrid_DataSource_PDO 0.1.1dev1: Invalid version string "0.1.1dev1"
Could not load Text_PathNavigator 0.1.0dev2: Invalid version string "0.1.0dev2"
Could not load Text_PathNavigator 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Services_Pingback 0.2.0dev2: Invalid version string "0.2.0dev2"
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear/net_ldap2 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Hydrating :: lib/pear-pear.php.net/Net_LDAP2 => auth-ldap/include
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/data/www/osticket/include/plugins/lib/pear-pear.php.net/Net_LDAP2): failed to open dir: No such file or directory' in /data/www/osticket/include/plugins/make.php:407
Stack trace:
#0 /data/www/osticket/include/plugins/make.php(407): RecursiveDirectoryIterator->__construct('/data/www/ostic...', 4096)
#1 /data/www/osticket/include/plugins/make.php(329): PluginBuilder->_hydrate()
#2 /data/www/osticket/include/plugins/make.php(251): PluginBuilder->run(Array, Array)
#3 /data/www/osticket/include/plugins/make.php(508): Module->_run('make.php')
#4 {main}
  thrown in /data/www/osticket/include/plugins/make.php on line 407
root@osticket:/data/www/osticket/include/plugins# 
```

If I edit the auth-ldap/plugin.php to ask for the package name "pear/Net_LDAP2" it does not work. Neither does "Net_LDAP2".

Downloading the package manually and dropping it in the right place works.

**Comment by ghost** [comment]
Changing the package to "pear-pear.php.net/Net_LDAP2" worked well!
it's working.
