### ISSUE TITLE
php make.php hydrate

### ISSUE THREAD

**Issue by EcomEric** [osTicket/osTicket-plugins#61]
This is what I get back when I try to run 'php make.php hydrate' from the include/plugins folder. I looked at a couple similar issues but didn't find a solution. 

---

Initializing PEAR repository http://pear.php.net
Could not load Auth 1.3.0r5: Invalid version string "1.3.0r5"
Could not load Auth 1.3.0r4: Invalid version string "1.3.0r4"
Could not load Auth 1.3.0r3: Invalid version string "1.3.0r3"
Could not load Auth 1.3.0r2: Invalid version string "1.3.0r2"
Could not load Auth 1.3.0r1: Invalid version string "1.3.0r1"
Could not load Auth_PrefManager2 2.0.0dev1: Invalid version string "2.0.0dev1"
Could not load Contact_AddressBook 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Gtk_ScrollingLabel 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Image_Graph 0.3.0dev4: Invalid version string "0.3.0dev4"
Could not load Image_Graph 0.3.0dev3: Invalid version string "0.3.0dev3"
Could not load Image_Graph 0.3.0dev2: Invalid version string "0.3.0dev2"
Could not load Image_Graph 0.3.0dev1: Invalid version string "0.3.0dev1"
Could not load Net_MPD 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load PEAR 1.9.5dev1: Invalid version string "1.9.5dev1"
Could not load Structures_DataGrid 0.9.1dev1: Invalid version string "0.9.1dev1"
Could not load Structures_DataGrid_DataSource_Array 0.2.0dev1: Invalid version string "0.2.0dev1"
Could not load Structures_DataGrid_DataSource_DataObject 0.2.2dev1: Invalid version string "0.2.2dev1"
Could not load Structures_DataGrid_DataSource_XML 0.2.1dev1: Invalid version string "0.2.1dev1"
Could not load Structures_DataGrid_Renderer_CSV 0.1.5dev1: Invalid version string "0.1.5dev1"
Could not load Structures_DataGrid_Renderer_XML 0.1.4dev1: Invalid version string "0.1.4dev1"
Could not load Structures_Form 0.8.0devel: Invalid version string "0.8.0devel"
Could not load Structures_Form_Gtk2 0.8.0devel: Invalid version string "0.8.0devel"
Could not load Structures_DataGrid_DataSource_PDO 0.1.1dev1: Invalid version string "0.1.1dev1"
Could not load Text_PathNavigator 0.1.0dev2: Invalid version string "0.1.0dev2"
Could not load Text_PathNavigator 0.1.0dev1: Invalid version string "0.1.0dev1"
Could not load Services_Pingback 0.2.0dev2: Invalid version string "0.2.0dev2"
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear/net_ldap2 could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
Hydrating :: lib/pear-pear.php.net/Net_LDAP2 => auth-ldap/include

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/Users/Eric/Servers/kmmfg/osTicket/include/plugins/lib/pear-pear.php.net/Net_LDAP2): failed to open dir: No such file or directory' in /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php:411
Stack trace:
#0 /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php(411): RecursiveDirectoryIterator->__construct('/Users/Eric/Ser...', 4096)
#1 /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php(322): PluginBuilder->_hydrate(Array)
#2 /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php(240): PluginBuilder->run(Array, Array)
#3 /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php(523): Module->_run('make.php')
#4 {main}

  thrown in /Users/Eric/Servers/kmmfg/osTicket/include/plugins/make.php on line 411

**Comment by greezybacon** [comment]
Ugh. Have you tried the ldap plugin from the osticket.com download page?

**Comment by EcomEric** [comment]
I've added the .phar file and tried again. Same error with this exception.

The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

**Comment by EcomEric** [comment]
[develop] ~/Servers/kmmfg/osTicket/include/plugins$ > ls -a
.       .git        README.md   auth-oauth  composer.phar   storage-fs
..      .gitignore  auth-ldap   auth-passthru   lib     storage-s3
.DS_Store   LICENSE     auth-ldap.phar      composer.json       make.php

**Comment by ntozier** [comment]
I'd recommend just grabbing the plugin from osticket.com/downloads from the plugin tab, which do not require hydrate to be run.

**Comment by EcomEric** [comment]
Well... I installed the plugins from the website and now I'm getting this on the front end

Warning: include(/Users/Eric/Servers/kmmfg/osTicket/include/plugins/storage-s3/plugin.php): failed to open stream: No such file or directory in /Users/Eric/Servers/kmmfg/osTicket/include/class.plugin.php on line 274

Warning: include(): Failed opening '/Users/Eric/Servers/kmmfg/osTicket/include/plugins/storage-s3/plugin.php' for inclusion (include_path='./:/Users/Eric/Servers/kmmfg/osTicket/include/:/Users/Eric/Servers/kmmfg/osTicket/include/pear/:/Users/Eric/Servers/kmmfg/osTicket/include/plugins/auth-ldap/include') in /Users/Eric/Servers/kmmfg/osTicket/include/class.plugin.php on line 274

Warning: array_merge(): Argument #2 is not an array in /Users/Eric/Servers/kmmfg/osTicket/include/class.plugin.php on line 274

Warning: Creating default object from empty value in /Users/Eric/Servers/kmmfg/osTicket/include/class.plugin.php on line 190

**Comment by EcomEric** [comment]
Ok, I deleted the reference to storage-s3 in the database and the warnings are gone.

**Comment by jeffsacco** [comment]
Just a quick question that relates to this one.  I did the same thing and I get the same error.  I am in need to make some alterations as a request from my firm on the data we want to get back from AD.  Downloading the plugin from the website is already in a compressed manner so I cannot make any changes to it without killing the site.

Kinda need to get this working. Any ideas to get php make.php hydrate working?

**Comment by ntozier** [comment]
You could just decompress the plugin.

**Comment by jeffsacco** [comment]
@ntozier That would be great. 

I am a little new at this.  How might I be able to decompress it?

**Comment by jeffsacco** [comment]
Well in my digging, I found a free service to decompress it.  Worked beautifully.

http://unphar.com/index.php

Now just need to find a way to compress it up again.

**Comment by ntozier** [comment]
Might I recommend to you to PHP's documentation on Phar and how to use it:
http://php.net/manual/en/book.phar.php

It includes documentation on how to make .phar files.

**Comment by jeffsacco** [comment]
Sure @ntozier I will give it a read over.  Just wondering why the installation instructions give that command but it errors out so much.  Not really understanding that portion of it

**Comment by ntozier** [comment]
I've been told to tell people to install using the official distributions from osticket.com/downloads. /shrug.

**Comment by jeffsacco** [comment]
ok no worries.  Will do that :)

**Comment by jeffsacco** [comment]
Ok, I figured out how to get rid of those errors

https://github.com/osTicket/core-plugins/issues/38

This solution does the trick

**Comment by jeffsacco** [comment]
Well I was able to solve the issue.

Turns out once you get hydrate working,  you should see this output:

Hydrating :: lib/pear-pear.php.net/Net_LDAP2 => auth-ldap/include
Hydrating :: lib/ohmy/auth/src => auth-oauth/lib

Then you know you are good when it comes to creating your phar file.  To actually get a phar file to generate, run this:

php make.php build auth-passthru

where auth-passthru is the directory you want to compress.  It will create the phar file in that directory.  I was then able to use it normally within OSTicket.

**Comment by cyjo** [comment]
https://github.com/cyjo/core-plugins/commit/46bfbf3e50ead9971ecad879c61086c4b7c1fa2a
