### ISSUE TITLE
Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct

### ISSUE THREAD

**Issue by sbgillett** [osTicket/osTicket-plugins#79]
When running php make.php hydrate under IIS I get

```
Uncaught exception 'UnexpectedValueException' with message     'RecursiveDirectoryIterator::__construct(C:\pathToOsTicket\include\plugins/lib/jasig/phpcas/source,C:    \pathToOsTicket\include\plugins/lib/jasig/phpcas/source): The system cannot find the path specified. (code: 3)' in C:\pathToOsTicket\include\plugins\make.php:481
Stack trace:
#0 C:\pathToOsTicket\include\plugins\make.php(481): RecursiveDirectoryIterator->__construct('C:\pathToOsTi...', 4096)
#1 C:\pathToOsTicket\include\plugins\make.php(340): PluginBuilder->_hydrate(Array)
#2 C:\pathToOsTicket\include\plugins\make.php(240): PluginBuilder->run(Array, Array)
#3 C:\pathToOsTicket\include\plugins\make.php(704): Module->_run('make.php')
#4 {main}
  thrown in C:\pathToOsTicket\include\plugins\make.php on line 481
```

Apologies in advance if this is an issue with my environment (:

**Comment by kensel** [comment]
I get the same error on my linux machine.

**Comment by FossPrime** [comment]
For me it was a low memory problem, composer complained higher up the log. Successfully ran on a headless centos 7 by shutting down the http, firewall and a couple misc cloud vendor processes.
