### ISSUE TITLE
auth-oauth plugin enabled and display the blank screen

### ISSUE THREAD

**Issue by kumarramalingam** [osTicket/osTicket-plugins#84]
auth-oauth plugin enabled after refresh the page display the blank screen.

Do the following steps 
1. Download the repository
2. Extract the zip folder and run the php make.php hydrate
3. Copy the files to /include/plugin

After go to admin panel. enable the auth-oauth plugin after refresh the page display the blank screen.

How to solve it?

**Comment by ntozier** [comment]
version of osTicket?
Version of PHP?
PHP error?

**Comment by kumarramalingam** [comment]
@ntozier 

Thanks for your response.

osTicket Version    v1.9.12
PHP Version     5.5.28

and 

am run this command : php make.php hydrate

Got this type of errors..

Hydrating :: lib/jasig/phpcas/source => auth-cas/lib/jasig/phpcas
PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/var/www/google_login/plugins/lib/jasig/phpcas/source): failed to open dir: No such file or directory' in /var/www/google_login/plugins/make.php:481
Stack trace:
#0 /var/www/google_login/plugins/make.php(481): RecursiveDirectoryIterator->__construct('/var/www/google...', 4096)
#1 /var/www/google_login/plugins/make.php(340): PluginBuilder->_hydrate(Array)
#2 /var/www/google_login/plugins/make.php(240): PluginBuilder->run(Array, Array)
#3 /var/www/google_login/plugins/make.php(704): Module->_run('make.php')
#4 {main} 

Thanks

**Comment by ntozier** [comment]
PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/var/www/google_login/plugins/lib/jasig/phpcas/source): failed to open dir: No such file or directory' in /var/www/google_login/plugins/make.php:481

This says that it failed to open a directory.  Specifically /var/www/google_login/plugins/lib/jasig/phpcas/source.  does it exist?

**Comment by kumarramalingam** [comment]
@ntozier 

Need step by step oauth2 installation.

**Comment by sasiryu** [comment]
Can any one please help on this ?

**Comment by ntozier** [comment]
@sasiryu Are you getting the same PHP error message?

**Comment by sasiryu** [comment]
Hi i fixed this by manually creating \lib\jasig\phpcas and pasting the contents got from the http://www.webpreprod.com/issue/utiliser-protocole-oauth-20-osticket-se-connecter-compte-google-facebook page. Still i have issue which i am following in #107 

Thanks a lot for help.

**Comment by Mukesh753** [comment]
The plugin doesn't seem to be working. I have entered Google + client id & secret
It takes me to this page and shows white blank page login.php?do=ext&bk=google.client
Os Ticket Version: Version 1.14.4
